# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
BigColSums2 <- function(X_) {
    .Call('_PUlasso_BigColSums2', PACKAGE = 'PUlasso', X_)
}

#'@export
LU_cpp <- function(X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, isSparse, verbose_) {
    .Call('_PUlasso_LU_cpp', PACKAGE = 'PUlasso', X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, isSparse, verbose_)
}

cv_LU_cpp <- function(X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, isSparse, verbose_, nfolds_, nfits_, ncores_) {
    .Call('_PUlasso_cv_LU_cpp', PACKAGE = 'PUlasso', X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, isSparse, verbose_, nfolds_, nfits_, ncores_)
}

#'@export
LU_big_cpp <- function(X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, verbose_) {
    .Call('_PUlasso_LU_big_cpp', PACKAGE = 'PUlasso', X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, verbose_)
}

#'@export
cv_LU_big_cpp <- function(X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, verbose_, nfolds_, nfits_, ncores_) {
    .Call('_PUlasso_cv_LU_big_cpp', PACKAGE = 'PUlasso', X_, z_, icoef_, gsize_, pen_, lambdaseq_, user_lambdaseq_, pathLength_, lambdaMinRatio_, pi_, maxit_, tol_, inner_tol_, useStrongSet_, verbose_, nfolds_, nfits_, ncores_)
}

#'@export
deviances_cpp <- function(coefMat_, X_, z_, pi_, isSparse) {
    .Call('_PUlasso_deviances_cpp', PACKAGE = 'PUlasso', coefMat_, X_, z_, pi_, isSparse)
}

